/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myDemoApp;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testNotNull() {
        int start = 20, end = 100;
        ArrayList<Integer> data = new ArrayList<>();
        assertNotNull(App.meaningfulMethod(start, end, data));
    }

    @Test
    public void testEmpty() {
        int start = 0, end = 0;
        ArrayList<Integer> data = new ArrayList<>();
        assertEquals(App.meaningfulMethod(start, end, data).size(), 0);
    }

    @Test
    public void testNotEmpty() {
        int start = 50, end = 150;
        ArrayList<Integer> data = new ArrayList<>();
        assertNotEquals(App.meaningfulMethod(start, end, data).size(), 0);
    }

    @Test
    public void testFound() {
        int start = 10, end = 50;
        int found = 21;
        ArrayList<Integer> data = new ArrayList<>();
        assertTrue(App.meaningfulMethod(start, end, data).contains(21));
    }

    @Test
    public void testNotFound() {
        int start = 40, end = 200;
        int notFound = 95;
        ArrayList<Integer> data = new ArrayList<>();
        assertFalse(App.meaningfulMethod(start, end, data).contains(95));
    }
}
